version: "3"
services:
  lab:
    image: mpxjpn_env:v01 
    container_name: jpt_container_mpxjpn 
    build:
        context: ./.devcontainer
        dockerfile: ./Dockerfile

    ports:
      - "8800:8888"

    volumes:
      - .:/home/jovyan/work

    command: start.sh jupyter lab